global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'scraper'
    static_configs:
      - targets: ['scraper:9410']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
